[package]
name = "fsrs-optimizer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = { git = "https://github.com/burn-rs/burn.git", version = "0.9.0" }
burn-ndarray = { git = "https://github.com/burn-rs/burn.git", version = "0.9.0" }

[[bin]]
name = "fsrs-optimizer-rust"
path = "main.rs"
