[package]
name = "fsrs-optimizer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
burn = "0.8.0"

[[bin]]
name = "fsrs-optimizer-rust"
path = "main.rs"
